name: scmr-park7-lusc
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - h5py>=3.11
  - lifelines>=0.29
  - matplotlib>=3.8
  - numpy>=1.26
  - pandas>=2.1
  - pillow>=10.0
  - scipy>=1.11
  - statsmodels>=0.14
